draw_config:
  append_colon_to_layer_header: false
  arc_radius: 6.0
  arc_scale: 1.0

  # combo box dimensions
  combo_h: 20.0
  combo_w: 20.0

  # Padding between keys
  inner_pad_h: 2.0
  inner_pad_w: 2.0

  # key dimensions, non-ortho layouts use key_h for width as well
  key_h: 56.0
  key_w: 60.0

  # keys border radius
  key_rx: 6.0
  key_ry: 6.0

  # key labels line spacing for multi-line labels
  line_spacing: 1.2

  # padding between layers
  outer_pad_h: 56.0
  outer_pad_w: 30.0

  # padding from the edge of cap to top and bottom legends
  small_pad: 2.0

  # gap between two halves for ortho layout generator
  split_gap: 10.0

  # Glyphs dimensions
  glyph_tap_size: 24
  glyph_hold_size: 14
  glyph_shifted_size: 18

  # shrink font size for legends wider than this many chars, set to 0 to disable
  # ideal value depends on the font size defined in svg_style and width of the boxes
  shrink_wide_legends: 2

  svg_style: |
    
    /* inherit to force styles through use tags */
    svg path {
        fill: inherit;
    }

    /* font and background color specifications */
    svg.keymap {
        /*
         * ====================
         * Theme Variables
         * ====================
         */

        --logo-path: none;
        --logo-size: 12%;
        --logo-position: 49.5% 5%;

        /* === Colors === */

        --color--material--blue--50: rgb(227, 242, 253);
        --color--material--blue--100: rgb(187, 222, 251);
        --color--material--blue--200: rgb(144, 202, 249);
        --color--material--blue--300: rgb(100, 181, 246);
        --color--material--blue--400: rgb(66, 165, 245);
        --color--material--blue--500: rgb(33, 150, 243);
        --color--material--blue--600: rgb(30, 136, 229);
        --color--material--blue--700: rgb(25, 118, 210);
        --color--material--blue--800: rgb(21, 101, 192);
        --color--material--blue--900: rgb(13, 71, 161);
        --color--material--blue--a100: rgb(130, 177, 255);
        --color--material--blue--a200: rgb(68, 138, 255);
        --color--material--blue--a400: rgb(41, 121, 255);
        --color--material--blue--a700: rgb(41, 98, 255);

        --color--material--blue-gray--50: rgb(236, 239, 241);
        --color--material--blue-gray--100: rgb(207, 216, 220);
        --color--material--blue-gray--200: rgb(176, 190, 197);
        --color--material--blue-gray--300: rgb(144, 164, 174);
        --color--material--blue-gray--400: rgb(120, 144, 156);
        --color--material--blue-gray--500: rgb(96, 125, 139);
        --color--material--blue-gray--600: rgb(84, 110, 122);
        --color--material--blue-gray--700: rgb(69, 90, 100);
        --color--material--blue-gray--800: rgb(55, 71, 79);
        --color--material--blue-gray--900: rgb(38, 50, 56);

        --color--material--blue-light--50: rgb(225, 245, 254);
        --color--material--blue-light--100: rgb(179, 229, 252);
        --color--material--blue-light--200: rgb(129, 212, 250);
        --color--material--blue-light--300: rgb(79, 195, 247);
        --color--material--blue-light--400: rgb(41, 182, 246);
        --color--material--blue-light--500: rgb(3, 169, 244);
        --color--material--blue-light--600: rgb(3, 155, 229);
        --color--material--blue-light--700: rgb(2, 136, 209);
        --color--material--blue-light--800: rgb(2, 119, 189);
        --color--material--blue-light--900: rgb(1, 87, 155);
        --color--material--blue-light--a100: rgb(128, 216, 255);
        --color--material--blue-light--a200: rgb(64, 196, 255);
        --color--material--blue-light--a400: rgb(0, 176, 255);
        --color--material--blue-light--a700: rgb(0, 145, 234);

        --color--material--purple--50: rgb(243, 229, 245);
        --color--material--purple--100: rgb(225, 190, 231);
        --color--material--purple--200: rgb(206, 147, 216);
        --color--material--purple--300: rgb(186, 104, 200);
        --color--material--purple--400: rgb(171, 71, 188);
        --color--material--purple--500: rgb(156, 39, 176);
        --color--material--purple--600: rgb(142, 36, 170);
        --color--material--purple--700: rgb(123, 31, 162);
        --color--material--purple--800: rgb(106, 27, 154);
        --color--material--purple--900: rgb(74, 20, 140);
        --color--material--purple--a100: rgb(234, 128, 252);
        --color--material--purple--a200: rgb(224, 64, 251);
        --color--material--purple--a400: rgb(213, 0, 249);
        --color--material--purple--a700: rgb(170, 0, 255);

        --color--material--red--50: rgb(255, 235, 238);
        --color--material--red--100: rgb(255, 205, 210);
        --color--material--red--200: rgb(239, 154, 154);
        --color--material--red--300: rgb(229, 115, 115);
        --color--material--red--400: rgb(239, 83, 80);
        --color--material--red--500: rgb(244, 67, 54);
        --color--material--red--600: rgb(229, 57, 53);
        --color--material--red--700: rgb(211, 47, 47);
        --color--material--red--800: rgb(198, 40, 40);
        --color--material--red--900: rgb(183, 28, 28);
        --color--material--red--a100: rgb(255, 138, 128);
        --color--material--red--a200: rgb(255, 82, 82);
        --color--material--red--a400: rgb(255, 23, 68);
        --color--material--red--a700: rgb(213, 0, 0);

        --color--material--teal--50: rgb(224, 242, 241);
        --color--material--teal--100: rgb(178, 223, 219);
        --color--material--teal--200: rgb(128, 203, 196);
        --color--material--teal--300: rgb(77, 182, 172);
        --color--material--teal--400: rgb(38, 166, 154);
        --color--material--teal--500: rgb(0, 150, 136);
        --color--material--teal--600: rgb(0, 137, 123);
        --color--material--teal--700: rgb(0, 121, 107);
        --color--material--teal--800: rgb(0, 105, 92);
        --color--material--teal--900: rgb(0, 77, 64);
        --color--material--teal--a100: rgb(167, 255, 235);
        --color--material--teal--a200: rgb(100, 255, 218);
        --color--material--teal--a400: rgb(29, 233, 182);
        --color--material--teal--a700: rgb(0, 191, 165);

        --color--material--yellow--50: rgb(255, 253, 231);
        --color--material--yellow--100: rgb(255, 249, 196);
        --color--material--yellow--200: rgb(255, 245, 157);
        --color--material--yellow--300: rgb(255, 241, 118);
        --color--material--yellow--400: rgb(255, 238, 88);
        --color--material--yellow--500: rgb(255, 235, 59);
        --color--material--yellow--600: rgb(253, 216, 53);
        --color--material--yellow--700: rgb(251, 192, 45);
        --color--material--yellow--800: rgb(249, 168, 37);
        --color--material--yellow--900: rgb(245, 127, 23);
        --color--material--yellow--a100: rgb(255, 255, 141);
        --color--material--yellow--a200: rgb(255, 255, 0);
        --color--material--yellow--a400: rgb(255, 234, 0);
        --color--material--yellow--a700: rgb(255, 214, 0);

        --color--turquoise--500: rgb(51, 204, 204);

        --color--bg: transparent;
        --color--text: var(--color--material--blue-gray--900);

        --color--layer--text: var(--color--material--blue-gray--400);

        --color--key--bg: var(--color--material--blue-gray--50);
        --color--key--border: white;
        --color--key--text--tap: var(--color--text);
        --color--key--text--shifted: var(--color--material--blue-gray--500);
        --color--key--text--hold: var(--color--material--blue-gray--500);

        --color--combo--bg: var(--color--material--blue-gray--100);
        --color--combo--border: var(--color--combo--bg);
        --color--combo--dendron: var(--color--combo--border);
        --color--combo--text--tap: var(--color--material--blue-gray--800);
        --color--combo--text--shifted: var(--color--material--blue-gray--400);
        --color--combo--text--hold: var(--color--combo--text--tap);

        --color--trans--bg: transparent;
        --color--trans--border: var(--color--material--blue-gray--400);
        --color--trans--text--tap: var(--color--trans--border);
        --color--trans--text--shifted: var(--color--trans--text--tap);
        --color--trans--text--hold: var(--color--trans--text--tap);

        --color--none--bg: var(--color--trans--bg);
        --color--none--border: var(--color--trans--border);
        --color--none--text--tap: var(--color--trans--text--tap);
        --color--none--text--shifted: var(--color--trans--text--shifted);
        --color--none--text--hold: var(--color--trans--text--hold);

        --color--ghost--bg: var(--color--trans--bg);
        --color--ghost--border: var(--color--trans--border);
        --color--ghost--text--tap: var(--color--trans--text--tap);
        --color--ghost--text--shifted: var(--color--trans--text--shifted);
        --color--ghost--text--hold: var(--color--trans--text--shifted);

        /*
         * ====================
         * /End Theme Variables
         * ====================
         */

        font-family: SFMono-Regular,Consolas,Liberation Mono,Menlo,monospace;
        font-size: 22px;
        font-kerning: normal;
        text-rendering: optimizeLegibility;
        fill: var(--color--text);
        background-color: var(--color--bg);
        background-image: var(--logo-path);
        background-repeat: no-repeat;
        background-position: var(--logo-position);
        background-size: var(--logo-size) auto;
    }

    /* default key styling */
    rect {
        fill: #f6f8fa;
        stroke: #c9cccf;
        stroke-width: 1;
    }

    /* color accent for combo boxes */
    rect.combo {
        fill: #cdf;
    }

    /* color accent for held keys */
    rect.held, rect.combo.held {
        fill: #fdd;
    }

    /* color accent for ghost (optional) keys */
    rect.ghost, rect.combo.ghost {
        fill: #ddd;
    }

    text {
        text-anchor: middle;
        dominant-baseline: middle;
    }

    /* styling for layer labels */
    text.label {
        font-weight: bold;
        text-anchor: start;
        stroke: white;
        stroke-width: 2;
        paint-order: stroke;
    }

    /* styling for combo tap, and key hold/shifted label text */
    text.combo, text.hold {
        font-size: 11px;
    }

    text.hold {
        text-anchor: middle;
        dominant-baseline: auto;
    }

    text.shifted {
        text-anchor: middle;
        dominant-baseline: hanging;
        font-size: 20px;
    }

    /* styling for hold/shifted label text in combo box */
    text.combo.hold, text.combo.shifted {
        font-size: 8px;
    }

    /* styling for combo dendrons */
    path {
        stroke-width: 1;
        stroke: gray;
        fill: none;
    }

parse_config:
  preprocess: true
  zmk_additional_includes: [ "zmk-helpers/include" ]
  zmk_remove_keycode_prefix: [ "SV_" ]
  raw_binding_map:
    '&gresc': 'Esc'
    '&td_caps': $$mdi:alpha-w-box$$
    '&reset': 'Reset'
    '&m_undo': '^-Z'
    '&m_cut': '^-X'
    '&m_copy': '^-C'
    '&m_paste': '^-V'

    '&macro_tilde': '~'
    '&macro_grave': '`'
    '&macro_caret': '^'
    'macro_tilde': '~'

    "&caps_word": $$mdi:alpha-w-box$$
    "&td_sftcap":
      tap: $$mdi:apple-keyboard-shift$$
      hold: $$mdi:alpha-w-box$$

    '&bootloader': 'Boot'
    '&esc_NAV': { t: 'Esc', h: 'NAV' }
    '&tab_NUM': { t: 'TAB', h: 'NUM' }
    '&ret_SYM': { t: 'Enter', h: 'SYM' }
    '&bspc_del':
      type: backspace
      tap: $$mdi:backspace$$
      shifted: $$mdi:backspace-reverse-outline$$

    '&slh_bslh': { t: '/', s: '\' }

    '&kp LG(Z)': '^Z'
    '&kp LG(C)': '^C'
    '&kp LG(V)': '^V'
    '&kp LG(X)': '^X'

    '&kp LG(F)': '^F'
    '&kp LG(A)': '^A'
    '&kp LG(S)': '^S'

    '&kp LS(TAB)': $$mdi:keyboard-tab-reverse$$

    '&kp LC(C_BRI_UP)': $$mdi:brightness-5$$
    '&kp LC(C_BRI_DN)': $$mdi:brightness-7$$

    '&kp LG(PLUS)': 'Zoom+'
    '&kp LG(MINUS)': 'Zoom-'
    '&kp LG(N0)': 'Zoom-0'
    '&kp LC(G)': 'Ctrl-G'
    '&kp LG(B)': 'Cmd-B'
    '&kp LA(BSPC)': 'Alt- Bspc'
    '&kp LG(LS(LBKT))': 'Back'
    '&kp LG(LS(RBKT))': 'Fwd'

    '&kp SV_SEMI': ';'

    # Zoom
    '&kp RG(RS(A))':
      tap: $$mdi:microphone$$
      hold: zoom
    '&kp RG(RS(V))':
      tap: $$mdi:video$$
      hold: zoom

  skip_binding_parsing: false
  sticky_label: '[sticky]'
  zmk_combos: {}
  zmk_keycode_map:
    # Modifiers
    LCTRL: $$mdi:apple-keyboard-control$$
    LALT: $$mdi:apple-keyboard-option$$
    LSHIFT: $$mdi:apple-keyboard-shift$$
    LSHFT: $$mdi:apple-keyboard-shift$$
    LCMD: $$mdi:apple-keyboard-command$$
    RCTRL: $$mdi:apple-keyboard-control$$
    RALT: $$mdi:apple-keyboard-option$$
    RSHIFT: $$mdi:apple-keyboard-shift$$
    RSHFT: $$mdi:apple-keyboard-shift$$
    RCMD: $$mdi:apple-keyboard-command$$
    LGUI: $$mdi:apple-keyboard-command$$
    RGUI: $$mdi:apple-keyboard-command$$

    # Arrows
    UP: $$mdi:arrow-up-bold$$
    DOWN: $$mdi:arrow-down-bold$$
    LEFT: $$mdi:arrow-left-bold$$
    RIGHT: $$mdi:arrow-right-bold$$

    # Whitespace
    ENTER:
      type: enter
      tap: $$mdi:keyboard-return$$
    RET:
      type: enter
      tap: $$mdi:keyboard-return$$
    ESC: $$mdi:keyboard-esc$$
    TAB: $$mdi:keyboard-tab$$
    #LS(TAB): $$mdi:keyboard-tab-reverse$$
    SPACE: $$mdi:keyboard-space$$
    BACKSPACE:
      type: backspace
      tap: $$mdi:backspace$$
    BSPC:
      type: backspace
      tap: $$mdi:backspace$$
    DELETE: $$mdi:backspace-reverse-outline$$
    DEL: $$mdi:backspace-reverse-outline$$

    # Locks
    CAPSLOCK: $$mdi:apple-keyboard-caps$$
    CAPS: $$mdi:apple-keyboard-caps$$

    # Sound
    C_MUTE: $$mdi:volume-off$$
    C_VOL_UP: $$mdi:volume-high$$
    C_VOL_DN: $$mdi:volume-low$$

    # Media
    C_NEXT: $$mdi:skip-next$$
    C_PREV: $$mdi:skip-previous$$
    C_PP: $$mdi:play-pause$$

    # Bluetooth
    BT_CLR: $$mdi:bluetooth-off$$
    BT_SEL: $$mdi:bluetooth-connect$$

    # Settings
    C_BRI_UP: $$mdi:brightness-5$$
    C_BRI_DN: $$mdi:brightness-7$$
    #LC(C_BRI_UP): $$mdi:brightness-5$$
    #LC(C_BRI_DN): $$mdi:brightness-7$$

    # System
    C_POWER: $$mdi:power-standby$$
    C_AL_LOCK: $$mdi:lock$$
    K_CANCEL: $$mdi:close-box$$

    PG_UP: "PgUp"
    PG_DN: "PgDn"
    HOME: "Home"
    END: "End"

    AMPERSAND: '&'
    AMPS: '&'
    APOS: .
    APOSTROPHE: <
    ASTERISK: '*'
    ASTRK: '*'
    AT: '@'
    AT_SIGN: '@'
    BACKSLASH: \
    BSLH: \
    CARET: ^
    COLON: ':'
    DLLR: $
    DOLLAR: $
    DOUBLE_QUOTES: '"'
    DQT: '"'
    EXCL: '!'
    EXCLAMATION: '!'
    FSLH: /
    GRAVE: '`'
    GREATER_THAN: '>'
    GT: '>'
    HASH: '#'
    LBKT: '['
    LBRC: '{'
    LEFT_BRACE: '{'
    LEFT_BRACKET: '['
    LEFT_PARENTHESIS: (
    LESS_THAN: <
    LPAR: (
    LT: <
    MINUS: '-'
    NON_US_BACKSLASH: \
    NON_US_BSLH: '|'
    NON_US_HASH: '#'
    NUHS: '#'
    PERCENT: '%'
    PERIOD: .
    PIPE: '|'
    PIPE2: '|'
    PLUS: +
    POUND: '#'
    PRCNT: '%'
    QMARK: '?'
    QUESTION: '?'
    RBKT: ']'
    RBRC: '}'
    RIGHT_BRACE: '}'
    RIGHT_BRACKET: ']'
    RIGHT_PARENTHESIS: )
    RPAR: )
    SEMICOLON: ;
    SINGLE_QUOTE: ''''
    SLASH: /
    STAR: '*'
    TILDE: '~'
    TILDE2: '~'
    UNDER: _
    UNDERSCORE: _

    A_RING: 'Å'
    A_UMLAUT: 'Ä'
    O_UMLAUT: 'Ö'
    SECT: '§'
    EURO: '€'
    COMMA: { t: ',', s: ';' }
    DOT: { t: '.', s: ':' }
    SQT: ''''
    EQUAL: '='
