# Example for using the keymap-drawer ZMK user config workflow
name: Draw ZMK keymaps
on:
  workflow_dispatch: # can be triggered manually
permissions: write-all

jobs:
  draw:
    uses: caksoylar/keymap-drawer/.github/workflows/draw-zmk.yml@main
    with:
      keymap_patterns: "config/totem.keymap" # path to the keymaps to parse
      config_path: "keymap_drawer.config.yaml" # config file, ignored if not exists
      output_folder: "svg" # path to save produced SVGs
      parse_args: "" #"totem:'-c 10'" # map of extra args to pass to `keymap parse`, e.g. "corne:'-l Def Lwr Rse' cradio:''"
      draw_args: "" #"totem:'-k corne_rotated -l LAYOUT_split_3x5_3'" # map of extra args to pass to `keymap draw`, e.g. "corne:'-k corne_rotated' cradio:'-k paroxysm'"   -o '{split: true, rows: 3, columns: 6, thumbs: 3}'
      install_branch: main # need this until the next release to get the latest keymap-drawer
      west_config_path: 'config'
